//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class kitaplarr
    {
        public int kitap_id { get; set; }
        public string kitap_ad { get; set; }
        public string kitap_yazar { get; set; }
        public string kitap_yayinevi { get; set; }
        public Nullable<System.DateTime> kitap_basimtarihi { get; set; }
        public Nullable<int> kitap_sayfasayisi { get; set; }
        public string kitap_turu { get; set; }
    }
}
