//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonWinForm
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class kutuphaneOtomasyonuEntities : DbContext
    {
        public kutuphaneOtomasyonuEntities()
            : base("name=kutuphaneOtomasyonuEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<personeller> personeller { get; set; }
        public virtual DbSet<kullanicilar> kullanicilar { get; set; }
        public virtual DbSet<kitaplarr> kitaplarr { get; set; }
        public virtual DbSet<kayitlar> kayitlar { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<MSchange_tracking_history> MSchange_tracking_history { get; set; }
    }
}
